### ISSUE TITLE
Error when trying to use

### ISSUE THREAD

**Issue by simonnarang** [mattdonnelly/Swifter#146] opened 2016-06-26 21:34 UTC
Hey there,
When I try to use the `urlEncodedString` piece of the String extension in the swift3 branch, I get the error `Abstract class Foundation._SwiftNSCharacterSet does not implement method mutableCopyWithZone:; it must be implemented in subclasses.`

**Comment by meteochu** [comment] 2016-06-27 03:15
That's a known problem with Swift 3 right now. Currently, `Foundation.CharacterSet` will break when you try to remove characters from the CharacterSet. It is not a bug with Swifter, and should be resolved when Swift 3 beta is updated down the line. You can read more about it on [rdar://26880260](http://www.openradar.me/26880260). 

Since it is not a Swifter bug, the only solution is to wait for Apple to fix Foundation.CharacterSet.

**Comment by meteochu** [comment] 2016-07-30 07:50
The latest Swift betas have fixed this. I am now closing this issue.

**Closed by meteochu** 2016-07-30 07:50 UTC
Labels: bug
