### ISSUE TITLE
2 tabs was opened at safali when called authorize function in Xcode11 beta.

### ISSUE THREAD

**Issue by kumanmushi** [mattdonnelly/Swifter#277] opened 2019-08-07 08:23 UTC
2 tabs was opened at Safali when called iOS authorize function in Xcode11 beta.
First tab is `https://api.twitter.com/oauth/authorize?oauth_token=[Token]`
Second tab is searched `oauth_token=[Token]`.
2tabs was random displayed.

**Comment by meteochu** [comment] 2019-09-22 06:13
Interesting issue. It seems like this is caused by opening URL created with relative urls. This issue has been fixed in d8ab61e.

**Closed by meteochu** 2019-09-22 06:13 UTC
