### ISSUE TITLE
Using JSON return values

### ISSUE THREAD

**Issue by arnav-gudibande** [mattdonnelly/Swifter#147] opened 2016-07-03 20:55 UTC
I'm new to the Swifter Framework and have a question regarding the Swifter public methods.

I realize that most of the methods return JSON values in the form of `statuses`, but I am unsure as to how to implement or use these values. For example, I am trying to get the user's profile banner by passing in the username as a parameter:

`self.swifter?.getUsersProfileBannerWithUserID(userName, success: { statuses in `
    `guard let decodedPicture = UIImage(statuses) else {return}`
`})`

However, the error "Some not found in type JSON" came up. In general, how would one go about using the Swifter framework for get requests and how can one implement it in fetching a user's banner image?

**Comment by meteochu** [comment] 2016-07-04 03:30
You have to check the API for [GET users/profile_banner](https://dev.twitter.com/rest/reference/get/users/profile_banner). In this case, if you wanted the image url for the `web_reinta` size, you do...

```swift
self.swifter?.getUsersProfileBannerWithUserID(userName, success: { json in
  guard let url = json["web_retina"]["url"].string else { return }
  // now you have the url
  guard let data = NSData(contentsOfURL: url), 
        let decodedImage = UIImage(data: data) else { return }
  // now you have the image by using `decodedImage`
})

```

**Comment by arnav-gudibande** [comment] 2016-07-05 05:20
@meteochu thanks for the link to the documentation

I have implemented the code you provided, but it doesn't seem to return any values.

![screen shot 2016-07-04 at 10 18 09 pm]
(https://cloud.githubusercontent.com/assets/15108659/16574571/3f6d6cdc-4235-11e6-854f-f722a873600b.png)

Setting the user's username, etc works well but it doesn't even reach any of the following print statements.

**Comment by meteochu** [comment] 2016-07-06 08:49
You are using `getUsersProfileBannerWithUserID:` which requires you to input the `userID` and not the `screen_name` (userName), you should look at `getUsersProfileBannerWIthScreenName:` instead.

**Comment by meteochu** [comment] 2016-07-30 07:49
The problem is answered and should also be solved, I am now closing this issue.

**Closed by meteochu** 2016-07-30 07:49 UTC
