### ISSUE TITLE
Unable to run demo app in OSX

### ISSUE THREAD

**Issue by baymac** [mattdonnelly/Swifter#301] opened 2020-04-05 02:29 UTC
I am unable to open in Xcode. When I open the project SwifterDemoMac it says `Couldn't open file`.

**Comment by meteochu** [comment] 2020-05-10 05:34
I'm not able to reproduce this. I can open `Swifter.xcodeproj`, select `SwifterDemoMac` and running it just fine on macOS 10.15.4; closing this.

**Closed by meteochu** 2020-05-10 05:34 UTC
